name : Workflow lors d'un push
on: push
jobs:
  # Définition de la première action à réaliser
  premier-job:
    # On précise le système d'exploitation (runner)
    runs-on: ubuntu-latest

    # On écrit ici les étapes de notre action
    steps:
      - name: Récupération de notre application
        uses: actions/checkout@v4      

      - name: installation des dépendances 
        run: npm install

      - name: build de l'application
        run: npm run build

      - name: test
        run: npm run test


name: Spring Boot Application

# Ce workflow s'exécute lors d'un push
on: push

jobs:
  build:
    # Le job s'exécute sur un runner Ubuntu
    runs-on: ubuntu-latest

    steps:
      # Récupération du code depuis le dépôt GitHub
      - name: Récupération de l'application
        uses: actions/checkout@v4

      # Installation de JDK 17 
      - name: Installation de JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Construction du projet Maven (sans exécuter les tests pour cette étape)
      - name: Construction du projet Maven
        run: mvn clean install -DskipTests

      # Exécution des tests Maven
      - name: Exécution des tests
        run: mvn test



